version: "3.9"

services:
  logdemo:
    image: python:3.11-slim
    container_name: logdemo
    working_dir: /app
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
    command: sh -c "pip install boto3 watchtower && python app.py"
    environment:
      LOGSTASH_HOST: "elk.tekbay.click"
      LOGSTASH_PORT: "5044"
      AWS_REGION: "us-east-1"
      CW_LOG_GROUP: "demo-app-logs"
      CW_LOG_STREAM: "lab-stream"
    restart: unless-stopped
